import { Judgment } from '@/types/judgment';
import { ActionItem } from '@/types/action';
import { DepartmentStats } from '@/types/department';

export const DEMO_JUDGMENTS: Judgment[] = [
  {
    id: 'j1',
    case_number: 'WP(C) 1284/2023',
    case_title: 'Citizens for Clean Air v. Union of India & Ors.',
    court: 'Supreme Court of India',
    bench: 'Hon\'ble Justice A.K. Singh, Hon\'ble Justice P.R. Mehta',
    date_of_judgment: '2024-03-15',
    pdf_url: '/demo/judgment1.pdf',
    status: 'extracted',
    created_at: '2024-03-16T09:00:00Z',
    action_count: 12,
    verified_count: 8,
    completed_count: 3,
  },
  {
    id: 'j2',
    case_number: 'CWP-PIL-47/2024',
    case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority',
    court: 'High Court of Delhi',
    bench: 'Hon\'ble Chief Justice S.L. Reddy',
    date_of_judgment: '2024-05-22',
    pdf_url: '/demo/judgment2.pdf',
    status: 'verified',
    created_at: '2024-05-23T11:00:00Z',
    action_count: 8,
    verified_count: 8,
    completed_count: 5,
  },
  {
    id: 'j3',
    case_number: 'SLP(Civil) 9821/2024',
    case_title: 'Right to Education Foundation v. State of Maharashtra',
    court: 'Supreme Court of India',
    bench: 'Hon\'ble Justice M.T. Krishnan, Hon\'ble Justice D. Sharma',
    date_of_judgment: '2024-07-10',
    pdf_url: '/demo/judgment3.pdf',
    status: 'extracting',
    created_at: '2024-07-11T14:00:00Z',
    action_count: 0,
    verified_count: 0,
    completed_count: 0,
  },
];

export const DEMO_ACTIONS: ActionItem[] = [
  {
    id: 'a1',
    judgment_id: 'j1',
    directive_text: 'The Ministry of Environment, Forest and Climate Change shall submit a comprehensive action plan for reducing particulate matter (PM2.5) levels to WHO standards in all Class-I cities within 90 days of this order.',
    department: 'Environment',
    deadline_raw: '90 days from order',
    deadline_iso: '2024-06-13',
    compliance_metric: 'Submission of action plan + PM2.5 measurement data',
    source_text: 'The Ministry of Environment, Forest and Climate Change shall submit a comprehensive action plan for reducing particulate matter (PM2.5) levels to WHO standards in all Class-I cities within 90 days of this order.',
    source_page: 4,
    source_bbox: { x1: 72, y1: 320, x2: 540, y2: 380, page: 4 },
    confidence: 0.94,
    priority: 'high',
    status: 'verified',
    assigned_to: 'MoEFCC Secretary',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India & Ors.', court: 'Supreme Court of India' },
  },
  {
    id: 'a2',
    judgment_id: 'j1',
    directive_text: 'The Central Pollution Control Board shall install real-time air quality monitoring stations in every municipal ward of cities with population exceeding 10 lakhs within 6 months.',
    department: 'Environment',
    deadline_raw: '6 months',
    deadline_iso: '2024-09-15',
    compliance_metric: 'Number of monitoring stations installed / Total wards',
    source_text: 'The Central Pollution Control Board shall install real-time air quality monitoring stations in every municipal ward of cities with population exceeding 10 lakhs within 6 months.',
    source_page: 5,
    source_bbox: { x1: 72, y1: 140, x2: 540, y2: 200, page: 5 },
    confidence: 0.88,
    priority: 'high',
    status: 'in_progress',
    assigned_to: 'CPCB Director',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India & Ors.', court: 'Supreme Court of India' },
  },
  {
    id: 'a3',
    judgment_id: 'j1',
    directive_text: 'The Ministry of Finance shall allocate a dedicated Clean Air Fund of INR 5,000 crore for implementation of air pollution control measures, with utilization reports submitted quarterly.',
    department: 'Finance',
    deadline_raw: 'Next Budget Session',
    deadline_iso: '2025-02-01',
    compliance_metric: 'Fund allocation + Quarterly utilization reports',
    source_text: 'The Ministry of Finance shall allocate a dedicated Clean Air Fund of INR 5,000 crore for implementation of air pollution control measures, with utilization reports submitted quarterly.',
    source_page: 7,
    source_bbox: { x1: 72, y1: 260, x2: 540, y2: 320, page: 7 },
    confidence: 0.79,
    priority: 'high',
    status: 'pending_verification',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India & Ors.', court: 'Supreme Court of India' },
  },
  {
    id: 'a4',
    judgment_id: 'j1',
    directive_text: 'State governments shall phase out all diesel vehicles older than 10 years from city limits and provide a scrappage incentive scheme within 1 year.',
    department: 'Infrastructure',
    deadline_raw: '1 year',
    deadline_iso: '2025-03-15',
    compliance_metric: 'Number of vehicles scrapped / Incentive scheme notification',
    source_text: 'State governments shall phase out all diesel vehicles older than 10 years from city limits and provide a scrappage incentive scheme within 1 year.',
    source_page: 9,
    source_bbox: { x1: 72, y1: 180, x2: 540, y2: 240, page: 9 },
    confidence: 0.91,
    priority: 'medium',
    status: 'verified',
    assigned_to: 'MoRTH Secretary',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India & Ors.', court: 'Supreme Court of India' },
  },
  {
    id: 'a5',
    judgment_id: 'j2',
    directive_text: 'Delhi Jal Board shall ensure zero discharge of untreated sewage into the Yamuna river by installing sewage treatment plants (STPs) with a combined capacity of at least 2,000 MLD within 18 months.',
    department: 'Environment',
    deadline_raw: '18 months',
    deadline_iso: '2025-11-22',
    compliance_metric: 'STP capacity installed (MLD) / Sewage discharge monitoring data',
    source_text: 'Delhi Jal Board shall ensure zero discharge of untreated sewage into the Yamuna river by installing sewage treatment plants (STPs) with a combined capacity of at least 2,000 MLD within 18 months.',
    source_page: 3,
    source_bbox: { x1: 72, y1: 400, x2: 540, y2: 460, page: 3 },
    confidence: 0.96,
    priority: 'high',
    status: 'assigned',
    assigned_to: 'DJB CEO',
    created_at: '2024-05-23T11:00:00Z',
    judgment: { case_number: 'CWP-PIL-47/2024', case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority', court: 'High Court of Delhi' },
  },
  {
    id: 'a6',
    judgment_id: 'j2',
    directive_text: 'The Department of Health shall establish 50 Occupational Health Centres in industrial areas along the Yamuna belt within 6 months to monitor health impact on workers and residents.',
    department: 'Health',
    deadline_raw: '6 months',
    deadline_iso: '2024-11-22',
    compliance_metric: 'Number of OHCs established / Monthly health surveillance reports',
    source_text: 'The Department of Health shall establish 50 Occupational Health Centres in industrial areas along the Yamuna belt within 6 months to monitor health impact on workers and residents.',
    source_page: 6,
    source_bbox: { x1: 72, y1: 220, x2: 540, y2: 280, page: 6 },
    confidence: 0.72,
    priority: 'medium',
    status: 'overdue',
    assigned_to: 'DHS Director',
    created_at: '2024-05-23T11:00:00Z',
    judgment: { case_number: 'CWP-PIL-47/2024', case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority', court: 'High Court of Delhi' },
  },
  {
    id: 'a7',
    judgment_id: 'j1',
    directive_text: 'Ministry of Education shall include air quality awareness modules in school curricula for Classes 6–10 across all CBSE and state board schools by the next academic session.',
    department: 'Education',
    deadline_raw: 'Next academic session (June 2025)',
    deadline_iso: '2025-06-01',
    compliance_metric: 'Curriculum notification issued + Schools covered percentage',
    source_text: 'Ministry of Education shall include air quality awareness modules in school curricula for Classes 6–10 across all CBSE and state board schools by the next academic session.',
    source_page: 11,
    source_bbox: { x1: 72, y1: 300, x2: 540, y2: 360, page: 11 },
    confidence: 0.83,
    priority: 'low',
    status: 'completed',
    assigned_to: 'NCERT Director',
    verified_by: 'admin@court.gov.in',
    verified_at: '2024-04-01T10:00:00Z',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India & Ors.', court: 'Supreme Court of India' },
  },
  {
    id: 'a8',
    judgment_id: 'j2',
    directive_text: 'The Ministry of Finance shall create a Yamuna Rejuvenation Fund corpus of INR 2,500 crore with inter-ministerial oversight committee and annual audit.',
    department: 'Finance',
    deadline_raw: '3 months',
    deadline_iso: '2024-08-22',
    compliance_metric: 'Fund notification + Oversight committee formed',
    source_text: 'The Ministry of Finance shall create a Yamuna Rejuvenation Fund corpus of INR 2,500 crore with inter-ministerial oversight committee and annual audit.',
    source_page: 8,
    source_bbox: { x1: 72, y1: 160, x2: 540, y2: 220, page: 8 },
    confidence: 0.55,
    priority: 'high',
    status: 'overdue',
    created_at: '2024-05-23T11:00:00Z',
    judgment: { case_number: 'CWP-PIL-47/2024', case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority', court: 'High Court of Delhi' },
  },
];

export const DEMO_DEPARTMENT_STATS: DepartmentStats[] = [
  {
    department: 'Environment',
    color_hex: '#2D6A4F',
    total: 8,
    completed: 3,
    in_progress: 2,
    overdue: 1,
    pending: 2,
    compliance_pct: 62,
    sparkline: [20, 28, 35, 40, 48, 55, 62],
  },
  {
    department: 'Finance',
    color_hex: '#D4831A',
    total: 5,
    completed: 1,
    in_progress: 1,
    overdue: 2,
    pending: 1,
    compliance_pct: 30,
    sparkline: [10, 15, 15, 20, 20, 28, 30],
  },
  {
    department: 'Health',
    color_hex: '#C1121F',
    total: 4,
    completed: 2,
    in_progress: 1,
    overdue: 1,
    pending: 0,
    compliance_pct: 55,
    sparkline: [30, 35, 40, 42, 48, 50, 55],
  },
  {
    department: 'Infrastructure',
    color_hex: '#888780',
    total: 6,
    completed: 4,
    in_progress: 1,
    overdue: 0,
    pending: 1,
    compliance_pct: 78,
    sparkline: [50, 55, 60, 65, 70, 75, 78],
  },
  {
    department: 'Education',
    color_hex: '#7F77DD',
    total: 3,
    completed: 3,
    in_progress: 0,
    overdue: 0,
    pending: 0,
    compliance_pct: 100,
    sparkline: [60, 70, 78, 85, 90, 95, 100],
  },
  {
    department: 'Home Affairs',
    color_hex: '#185FA5',
    total: 2,
    completed: 0,
    in_progress: 1,
    overdue: 0,
    pending: 1,
    compliance_pct: 25,
    sparkline: [5, 8, 12, 15, 18, 22, 25],
  },
];
