import { Judgment } from '@/types/judgment';
import { ActionItem } from '@/types/action';
import { DepartmentStats } from '@/types/department';

export const DEMO_JUDGMENTS: Judgment[] = [
  {
    id: 'j1',
    case_number: 'WP(C) 1284/2023',
    case_title: 'Citizens for Clean Air v. Union of India & Ors.',
    court: 'Supreme Court of India',
    bench: 'Hon\'ble Justice A.K. Singh, Hon\'ble Justice P.R. Mehta',
    date_of_judgment: '2024-03-15',
    pdf_url: '/ccms/judgment1.pdf',
    status: 'verified',
    created_at: '2024-03-16T09:00:00Z',
    action_count: 14,
    verified_count: 14,
    completed_count: 9,
  },
  {
    id: 'j2',
    case_number: 'CWP-PIL-47/2024',
    case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority & Ors.',
    court: 'High Court of Delhi',
    bench: 'Hon\'ble Chief Justice S.L. Reddy, Hon\'ble Justice K. Menon',
    date_of_judgment: '2024-05-22',
    pdf_url: '/ccms/judgment2.pdf',
    status: 'verified',
    created_at: '2024-05-23T11:00:00Z',
    action_count: 10,
    verified_count: 10,
    completed_count: 6,
  },
  {
    id: 'j3',
    case_number: 'SLP(Civil) 9821/2024',
    case_title: 'Right to Education Foundation v. State of Maharashtra & Ors.',
    court: 'Supreme Court of India',
    bench: 'Hon\'ble Justice M.T. Krishnan, Hon\'ble Justice D. Sharma',
    date_of_judgment: '2024-07-10',
    pdf_url: '/ccms/judgment3.pdf',
    status: 'extracted',
    created_at: '2024-07-11T14:00:00Z',
    action_count: 9,
    verified_count: 7,
    completed_count: 2,
  },
  {
    id: 'j4',
    case_number: 'WP(C) 8435/2022',
    case_title: 'National Road Safety Council v. Ministry of Road Transport & Ors.',
    court: 'Supreme Court of India',
    bench: 'Hon\'ble Justice R. Gupta, Hon\'ble Justice N. Iyer',
    date_of_judgment: '2023-11-08',
    pdf_url: '/ccms/judgment4.pdf',
    status: 'verified',
    created_at: '2023-11-09T10:30:00Z',
    action_count: 11,
    verified_count: 11,
    completed_count: 8,
  },
  {
    id: 'j5',
    case_number: 'PIL No. 12/2023',
    case_title: 'Jan Swasthya Abhiyan v. State of Uttar Pradesh & Union of India',
    court: 'High Court of Allahabad',
    bench: 'Hon\'ble Justice S. Verma, Hon\'ble Justice A. Pandey',
    date_of_judgment: '2023-09-14',
    pdf_url: '/ccms/judgment5.pdf',
    status: 'verified',
    created_at: '2023-09-15T08:00:00Z',
    action_count: 8,
    verified_count: 8,
    completed_count: 5,
  },
  {
    id: 'j6',
    case_number: 'CWP 891/2024',
    case_title: 'Digital Inclusion Forum v. Ministry of Electronics & IT',
    court: 'High Court of Delhi',
    bench: 'Hon\'ble Justice P. Kaul',
    date_of_judgment: '2024-09-03',
    pdf_url: '/ccms/judgment6.pdf',
    status: 'extracted',
    created_at: '2024-09-04T13:00:00Z',
    action_count: 7,
    verified_count: 4,
    completed_count: 1,
  },
  {
    id: 'j7',
    case_number: 'WP(C) 15632/2023',
    case_title: 'Tribal Welfare Society v. Union of India & Ministry of Health',
    court: 'Supreme Court of India',
    bench: 'Hon\'ble Justice B.R. Naik, Hon\'ble Justice S. Chopra',
    date_of_judgment: '2024-01-25',
    pdf_url: '/ccms/judgment7.pdf',
    status: 'verified',
    created_at: '2024-01-26T09:00:00Z',
    action_count: 10,
    verified_count: 10,
    completed_count: 4,
  },
  {
    id: 'j8',
    case_number: 'SLP(Civil) 4471/2024',
    case_title: 'Mumbai Urban Resilience Foundation v. MCGM & State of Maharashtra',
    court: 'High Court of Bombay',
    bench: 'Hon\'ble Justice V. Deshmukh, Hon\'ble Justice P. Joshi',
    date_of_judgment: '2024-11-12',
    pdf_url: '/ccms/judgment8.pdf',
    status: 'extracting',
    created_at: '2024-11-13T16:00:00Z',
    action_count: 0,
    verified_count: 0,
    completed_count: 0,
  },
];

export const DEMO_ACTIONS: ActionItem[] = [
  // --- j1: Clean Air ---
  {
    id: 'a1',
    judgment_id: 'j1',
    directive_text: 'The Ministry of Environment, Forest and Climate Change shall submit a comprehensive action plan for reducing particulate matter (PM2.5) levels to WHO standards in all Class-I cities within 90 days of this order.',
    department: 'Environment',
    deadline_raw: '90 days from order',
    deadline_iso: '2024-06-13',
    compliance_metric: 'Submission of action plan + PM2.5 measurement data across Class-I cities',
    source_text: 'MoEFCC shall submit a comprehensive action plan for reducing PM2.5 levels to WHO standards in all Class-I cities within 90 days.',
    source_page: 4,
    source_bbox: { x1: 72, y1: 320, x2: 540, y2: 380, page: 4 },
    confidence: 0.94,
    priority: 'high',
    status: 'completed',
    assigned_to: 'MoEFCC Secretary',
    verified_by: 'registrar@supremecourt.gov.in',
    verified_at: '2024-03-20T10:00:00Z',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India', court: 'Supreme Court of India' },
  },
  {
    id: 'a2',
    judgment_id: 'j1',
    directive_text: 'The Central Pollution Control Board shall install real-time air quality monitoring stations in every municipal ward of cities with population exceeding 10 lakhs within 6 months.',
    department: 'Environment',
    deadline_raw: '6 months',
    deadline_iso: '2024-09-15',
    compliance_metric: 'Monitoring stations installed / Total wards',
    source_text: 'CPCB shall install real-time AQM stations in every municipal ward of cities >10 lakh population within 6 months.',
    source_page: 5,
    source_bbox: { x1: 72, y1: 140, x2: 540, y2: 200, page: 5 },
    confidence: 0.88,
    priority: 'high',
    status: 'completed',
    assigned_to: 'CPCB Director General',
    verified_by: 'registrar@supremecourt.gov.in',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India', court: 'Supreme Court of India' },
  },
  {
    id: 'a3',
    judgment_id: 'j1',
    directive_text: 'The Ministry of Finance shall allocate a dedicated Clean Air Fund of INR 5,000 crore for implementation of air pollution control measures, with utilization reports submitted quarterly.',
    department: 'Finance',
    deadline_raw: 'Next Budget Session',
    deadline_iso: '2025-02-01',
    compliance_metric: 'Fund allocation notification + Quarterly utilization reports',
    source_text: 'Ministry of Finance shall allocate Clean Air Fund of INR 5,000 crore with quarterly utilization reports.',
    source_page: 7,
    source_bbox: { x1: 72, y1: 260, x2: 540, y2: 320, page: 7 },
    confidence: 0.79,
    priority: 'high',
    status: 'in_progress',
    assigned_to: 'Additional Secretary, MoF',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India', court: 'Supreme Court of India' },
  },
  {
    id: 'a4',
    judgment_id: 'j1',
    directive_text: 'State governments shall phase out all diesel vehicles older than 10 years from city limits and provide a scrappage incentive scheme within 1 year.',
    department: 'Infrastructure',
    deadline_raw: '1 year',
    deadline_iso: '2025-03-15',
    compliance_metric: 'Number of vehicles scrapped / Incentive scheme notification issued',
    source_text: 'State govts shall phase out diesel vehicles older than 10 years and provide scrappage incentive within 1 year.',
    source_page: 9,
    source_bbox: { x1: 72, y1: 180, x2: 540, y2: 240, page: 9 },
    confidence: 0.91,
    priority: 'medium',
    status: 'in_progress',
    assigned_to: 'MoRTH Joint Secretary',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India', court: 'Supreme Court of India' },
  },
  {
    id: 'a5',
    judgment_id: 'j1',
    directive_text: 'Ministry of Education shall include air quality awareness modules in school curricula for Classes 6–10 across all CBSE and state board schools by the next academic session.',
    department: 'Education',
    deadline_raw: 'Next academic session (June 2025)',
    deadline_iso: '2025-06-01',
    compliance_metric: 'Curriculum notification issued + Schools covered percentage',
    source_text: 'MoE shall include air quality awareness in school curricula for Classes 6-10 by next academic session.',
    source_page: 11,
    source_bbox: { x1: 72, y1: 300, x2: 540, y2: 360, page: 11 },
    confidence: 0.83,
    priority: 'low',
    status: 'completed',
    assigned_to: 'NCERT Director',
    verified_by: 'admin@court.gov.in',
    verified_at: '2024-04-01T10:00:00Z',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India', court: 'Supreme Court of India' },
  },
  {
    id: 'a6',
    judgment_id: 'j1',
    directive_text: 'The Ministry of Health and Family Welfare shall establish an Air Pollution Health Registry tracking AQI-linked respiratory illness admissions in all district hospitals within 1 year.',
    department: 'Health',
    deadline_raw: '1 year',
    deadline_iso: '2025-03-15',
    compliance_metric: 'Registry portal launched + District hospital data integration count',
    source_text: 'MoHFW shall establish Air Pollution Health Registry in all district hospitals within 1 year.',
    source_page: 13,
    source_bbox: { x1: 72, y1: 420, x2: 540, y2: 480, page: 13 },
    confidence: 0.86,
    priority: 'medium',
    status: 'verified',
    assigned_to: 'DG Health Services',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India', court: 'Supreme Court of India' },
  },
  // --- j2: Yamuna River ---
  {
    id: 'a7',
    judgment_id: 'j2',
    directive_text: 'Delhi Jal Board shall ensure zero discharge of untreated sewage into the Yamuna river by installing sewage treatment plants (STPs) with a combined capacity of at least 2,000 MLD within 18 months.',
    department: 'Environment',
    deadline_raw: '18 months',
    deadline_iso: '2025-11-22',
    compliance_metric: 'STP capacity installed (MLD) / Sewage discharge monitoring data',
    source_text: 'DJB shall ensure zero untreated sewage into Yamuna; install STPs of 2,000 MLD within 18 months.',
    source_page: 3,
    source_bbox: { x1: 72, y1: 400, x2: 540, y2: 460, page: 3 },
    confidence: 0.96,
    priority: 'high',
    status: 'in_progress',
    assigned_to: 'Delhi Jal Board CEO',
    created_at: '2024-05-23T11:00:00Z',
    judgment: { case_number: 'CWP-PIL-47/2024', case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority', court: 'High Court of Delhi' },
  },
  {
    id: 'a8',
    judgment_id: 'j2',
    directive_text: 'The Department of Health shall establish 50 Occupational Health Centres in industrial areas along the Yamuna belt within 6 months to monitor health impact on workers and residents.',
    department: 'Health',
    deadline_raw: '6 months',
    deadline_iso: '2024-11-22',
    compliance_metric: 'Number of OHCs established / Monthly health surveillance reports',
    source_text: 'Dept of Health shall establish 50 OHCs in industrial areas along Yamuna belt within 6 months.',
    source_page: 6,
    source_bbox: { x1: 72, y1: 220, x2: 540, y2: 280, page: 6 },
    confidence: 0.72,
    priority: 'medium',
    status: 'overdue',
    assigned_to: 'Delhi Health Secretary',
    created_at: '2024-05-23T11:00:00Z',
    judgment: { case_number: 'CWP-PIL-47/2024', case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority', court: 'High Court of Delhi' },
  },
  {
    id: 'a9',
    judgment_id: 'j2',
    directive_text: 'The Ministry of Finance shall create a Yamuna Rejuvenation Fund corpus of INR 2,500 crore with inter-ministerial oversight committee and annual audit by independent agency.',
    department: 'Finance',
    deadline_raw: '3 months',
    deadline_iso: '2024-08-22',
    compliance_metric: 'Fund notification gazetted + Oversight committee constituted',
    source_text: 'MoF shall create Yamuna Rejuvenation Fund of INR 2,500 crore with inter-ministerial oversight and annual audit.',
    source_page: 8,
    source_bbox: { x1: 72, y1: 160, x2: 540, y2: 220, page: 8 },
    confidence: 0.55,
    priority: 'high',
    status: 'overdue',
    created_at: '2024-05-23T11:00:00Z',
    judgment: { case_number: 'CWP-PIL-47/2024', case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority', court: 'High Court of Delhi' },
  },
  {
    id: 'a10',
    judgment_id: 'j2',
    directive_text: 'The Delhi Development Authority shall relocate all encroachments within 100 metres of Yamuna floodplains and restore natural riparian vegetation over 1,200 hectares within 2 years.',
    department: 'Infrastructure',
    deadline_raw: '2 years',
    deadline_iso: '2026-05-22',
    compliance_metric: 'Hectares restored / Encroachments removed with rehabilitation proof',
    source_text: 'DDA shall relocate all Yamuna floodplain encroachments and restore 1,200 ha of riparian vegetation within 2 years.',
    source_page: 11,
    source_bbox: { x1: 72, y1: 340, x2: 540, y2: 400, page: 11 },
    confidence: 0.89,
    priority: 'high',
    status: 'assigned',
    assigned_to: 'DDA Vice Chairman',
    created_at: '2024-05-23T11:00:00Z',
    judgment: { case_number: 'CWP-PIL-47/2024', case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority', court: 'High Court of Delhi' },
  },
  {
    id: 'a11',
    judgment_id: 'j2',
    directive_text: 'The Ministry of Home Affairs shall constitute a dedicated River Crimes Unit within the Delhi Police to investigate and prosecute illegal dumping and industrial effluent discharge into the Yamuna.',
    department: 'Home Affairs',
    deadline_raw: '3 months',
    deadline_iso: '2024-08-22',
    compliance_metric: 'River Crimes Unit notification + First FIRs registered',
    source_text: 'MHA shall constitute River Crimes Unit in Delhi Police for prosecuting illegal discharge into Yamuna.',
    source_page: 14,
    source_bbox: { x1: 72, y1: 280, x2: 540, y2: 340, page: 14 },
    confidence: 0.77,
    priority: 'medium',
    status: 'completed',
    assigned_to: 'Delhi Police Commissioner',
    verified_by: 'admin@delhihc.gov.in',
    created_at: '2024-05-23T11:00:00Z',
    judgment: { case_number: 'CWP-PIL-47/2024', case_title: 'Yamuna Nadi Bachao Samiti v. Delhi NCR Authority', court: 'High Court of Delhi' },
  },
  // --- j3: Right to Education ---
  {
    id: 'a12',
    judgment_id: 'j3',
    directive_text: 'The State of Maharashtra shall ensure 100% enrollment of children aged 6–14 in government and aided schools in 20 underserved districts within 6 months, with door-to-door survey documentation.',
    department: 'Education',
    deadline_raw: '6 months',
    deadline_iso: '2025-01-10',
    compliance_metric: 'Enrollment percentage + Survey completion rate across 20 districts',
    source_text: 'Maharashtra shall ensure 100% enrollment of 6-14 yr children in underserved districts within 6 months.',
    source_page: 5,
    source_bbox: { x1: 72, y1: 200, x2: 540, y2: 260, page: 5 },
    confidence: 0.92,
    priority: 'high',
    status: 'in_progress',
    assigned_to: 'Maharashtra Education Secretary',
    created_at: '2024-07-11T14:00:00Z',
    judgment: { case_number: 'SLP(Civil) 9821/2024', case_title: 'Right to Education Foundation v. State of Maharashtra', court: 'Supreme Court of India' },
  },
  {
    id: 'a13',
    judgment_id: 'j3',
    directive_text: 'Ministry of Finance shall disburse pending RTE reimbursement dues of INR 1,840 crore to private unaided schools in Maharashtra within 8 weeks of this order.',
    department: 'Finance',
    deadline_raw: '8 weeks',
    deadline_iso: '2024-09-05',
    compliance_metric: 'Total amount disbursed / Schools covered + Utilization certificates',
    source_text: 'Ministry of Finance shall disburse pending RTE reimbursements of INR 1,840 crore within 8 weeks.',
    source_page: 8,
    source_bbox: { x1: 72, y1: 140, x2: 540, y2: 200, page: 8 },
    confidence: 0.81,
    priority: 'high',
    status: 'overdue',
    created_at: '2024-07-11T14:00:00Z',
    judgment: { case_number: 'SLP(Civil) 9821/2024', case_title: 'Right to Education Foundation v. State of Maharashtra', court: 'Supreme Court of India' },
  },
  // --- j4: Road Safety ---
  {
    id: 'a14',
    judgment_id: 'j4',
    directive_text: 'The National Highways Authority of India shall complete installation of rumble strips, crash barriers, and retroreflective signage on all 4-lane highways with accident frequency index above 0.5 within 9 months.',
    department: 'Infrastructure',
    deadline_raw: '9 months',
    deadline_iso: '2024-08-08',
    compliance_metric: 'Lane-km covered / Total blackspot km treated',
    source_text: 'NHAI shall install road safety infrastructure on highways with AFI >0.5 within 9 months.',
    source_page: 6,
    source_bbox: { x1: 72, y1: 300, x2: 540, y2: 360, page: 6 },
    confidence: 0.93,
    priority: 'high',
    status: 'completed',
    assigned_to: 'NHAI Chairman',
    verified_by: 'registrar@supremecourt.gov.in',
    created_at: '2023-11-09T10:30:00Z',
    judgment: { case_number: 'WP(C) 8435/2022', case_title: 'National Road Safety Council v. Ministry of Road Transport', court: 'Supreme Court of India' },
  },
  {
    id: 'a15',
    judgment_id: 'j4',
    directive_text: 'Ministry of Health and Family Welfare shall set up Trauma Care Centres at every 50 km interval on National Highways in all 36 states and UTs with trained paramedics and Golden Hour protocol within 1 year.',
    department: 'Health',
    deadline_raw: '1 year',
    deadline_iso: '2024-11-08',
    compliance_metric: 'Trauma centres operational / 50 km stretches covered',
    source_text: 'MoHFW shall set up Trauma Care Centres at 50 km intervals on all NHs within 1 year.',
    source_page: 9,
    source_bbox: { x1: 72, y1: 180, x2: 540, y2: 240, page: 9 },
    confidence: 0.87,
    priority: 'high',
    status: 'completed',
    assigned_to: 'Emergency Health Services Director',
    created_at: '2023-11-09T10:30:00Z',
    judgment: { case_number: 'WP(C) 8435/2022', case_title: 'National Road Safety Council v. Ministry of Road Transport', court: 'Supreme Court of India' },
  },
  {
    id: 'a16',
    judgment_id: 'j4',
    directive_text: 'Ministry of Home Affairs shall mandate body-worn cameras for all traffic police personnel on national and state highways within 6 months and establish a real-time incident reporting dashboard.',
    department: 'Home Affairs',
    deadline_raw: '6 months',
    deadline_iso: '2024-05-08',
    compliance_metric: 'Cameras deployed / Total traffic personnel + Dashboard uptime percentage',
    source_text: 'MHA shall mandate body-worn cameras for all highway traffic police and establish real-time incident dashboard within 6 months.',
    source_page: 12,
    source_bbox: { x1: 72, y1: 400, x2: 540, y2: 460, page: 12 },
    confidence: 0.74,
    priority: 'medium',
    status: 'completed',
    assigned_to: 'Inspector General, Traffic',
    verified_by: 'registrar@supremecourt.gov.in',
    created_at: '2023-11-09T10:30:00Z',
    judgment: { case_number: 'WP(C) 8435/2022', case_title: 'National Road Safety Council v. Ministry of Road Transport', court: 'Supreme Court of India' },
  },
  // --- j5: Jan Swasthya / Drinking Water ---
  {
    id: 'a17',
    judgment_id: 'j5',
    directive_text: 'The State of Uttar Pradesh shall ensure functional piped drinking water connections to all 97,000 revenue villages under Jal Jeevan Mission by March 2025, submitting monthly progress reports to this court.',
    department: 'Water Resources',
    deadline_raw: 'March 2025',
    deadline_iso: '2025-03-31',
    compliance_metric: 'Villages covered % + Monthly court compliance reports',
    source_text: 'UP shall provide piped water to all 97,000 revenue villages under JJM by March 2025 with monthly reports.',
    source_page: 4,
    source_bbox: { x1: 72, y1: 240, x2: 540, y2: 300, page: 4 },
    confidence: 0.91,
    priority: 'high',
    status: 'in_progress',
    assigned_to: 'UP Jal Nigam CEO',
    created_at: '2023-09-15T08:00:00Z',
    judgment: { case_number: 'PIL No. 12/2023', case_title: 'Jan Swasthya Abhiyan v. State of Uttar Pradesh', court: 'High Court of Allahabad' },
  },
  {
    id: 'a18',
    judgment_id: 'j5',
    directive_text: 'The Ministry of Finance shall release pending Jal Jeevan Mission grants of INR 4,200 crore to Uttar Pradesh within 30 days and provide a utilization-linked disbursement schedule for the remaining fiscal year.',
    department: 'Finance',
    deadline_raw: '30 days',
    deadline_iso: '2023-10-14',
    compliance_metric: 'Grant release letter + Disbursement schedule submitted',
    source_text: 'MoF shall release INR 4,200 crore JJM grants to UP within 30 days with disbursement schedule.',
    source_page: 7,
    source_bbox: { x1: 72, y1: 320, x2: 540, y2: 380, page: 7 },
    confidence: 0.88,
    priority: 'high',
    status: 'completed',
    assigned_to: 'Additional Secretary, Jal Shakti Ministry',
    verified_by: 'registrar@allahabadhc.gov.in',
    created_at: '2023-09-15T08:00:00Z',
    judgment: { case_number: 'PIL No. 12/2023', case_title: 'Jan Swasthya Abhiyan v. State of Uttar Pradesh', court: 'High Court of Allahabad' },
  },
  {
    id: 'a19',
    judgment_id: 'j5',
    directive_text: 'The Department of Health in Uttar Pradesh shall conduct water quality testing in all newly connected villages every quarter and publicly disclose results on a dedicated portal within 3 months.',
    department: 'Health',
    deadline_raw: '3 months',
    deadline_iso: '2023-12-14',
    compliance_metric: 'Portal launched + Villages tested per quarter',
    source_text: 'UP Health Dept shall conduct quarterly water quality testing in all connected villages and publish results within 3 months.',
    source_page: 9,
    source_bbox: { x1: 72, y1: 160, x2: 540, y2: 220, page: 9 },
    confidence: 0.76,
    priority: 'medium',
    status: 'completed',
    assigned_to: 'UP CMHO',
    created_at: '2023-09-15T08:00:00Z',
    judgment: { case_number: 'PIL No. 12/2023', case_title: 'Jan Swasthya Abhiyan v. State of Uttar Pradesh', court: 'High Court of Allahabad' },
  },
  // --- j6: Digital Access ---
  {
    id: 'a20',
    judgment_id: 'j6',
    directive_text: 'The Ministry of Electronics and IT shall mandate WCAG 2.1 AA compliance for all central government websites and mobile applications and conduct third-party accessibility audits within 6 months.',
    department: 'Infrastructure',
    deadline_raw: '6 months',
    deadline_iso: '2025-03-03',
    compliance_metric: 'Websites audited and compliant / Total central govt web properties',
    source_text: 'MeitY shall mandate WCAG 2.1 AA compliance for all central govt websites and apps within 6 months.',
    source_page: 3,
    source_bbox: { x1: 72, y1: 200, x2: 540, y2: 260, page: 3 },
    confidence: 0.84,
    priority: 'high',
    status: 'in_progress',
    assigned_to: 'MeitY Joint Secretary',
    created_at: '2024-09-04T13:00:00Z',
    judgment: { case_number: 'CWP 891/2024', case_title: 'Digital Inclusion Forum v. Ministry of Electronics & IT', court: 'High Court of Delhi' },
  },
  {
    id: 'a21',
    judgment_id: 'j6',
    directive_text: 'The Ministry of Finance shall allocate INR 800 crore under PM eVIDYA for procurement and distribution of Braille-enabled tablets and screen-reader software to 4 lakh visually impaired students by next fiscal year.',
    department: 'Finance',
    deadline_raw: 'FY 2025-26',
    deadline_iso: '2026-03-31',
    compliance_metric: 'Tablets procured and distributed + Students covered',
    source_text: 'MoF shall allocate INR 800 crore for Braille tablets and screen-reader software to 4 lakh visually impaired students.',
    source_page: 6,
    source_bbox: { x1: 72, y1: 360, x2: 540, y2: 420, page: 6 },
    confidence: 0.69,
    priority: 'medium',
    status: 'pending_verification',
    created_at: '2024-09-04T13:00:00Z',
    judgment: { case_number: 'CWP 891/2024', case_title: 'Digital Inclusion Forum v. Ministry of Electronics & IT', court: 'High Court of Delhi' },
  },
  // --- j7: Tribal Healthcare ---
  {
    id: 'a22',
    judgment_id: 'j7',
    directive_text: 'The Ministry of Health and Family Welfare shall operationalise at least one functional Primary Health Centre with a full-time MBBS doctor in every tribal block across Scheduled Areas within 1 year.',
    department: 'Health',
    deadline_raw: '1 year',
    deadline_iso: '2025-01-25',
    compliance_metric: 'PHCs with full-time MBBS doctors / Total tribal blocks in Scheduled Areas',
    source_text: 'MoHFW shall operationalise one functional PHC with MBBS doctor in every tribal block within 1 year.',
    source_page: 5,
    source_bbox: { x1: 72, y1: 280, x2: 540, y2: 340, page: 5 },
    confidence: 0.90,
    priority: 'high',
    status: 'in_progress',
    assigned_to: 'Director, National Health Mission',
    created_at: '2024-01-26T09:00:00Z',
    judgment: { case_number: 'WP(C) 15632/2023', case_title: 'Tribal Welfare Society v. Union of India & Ministry of Health', court: 'Supreme Court of India' },
  },
  {
    id: 'a23',
    judgment_id: 'j7',
    directive_text: 'The Ministry of Finance shall release scheduled Tribal Sub-Plan (TSP) health allocations of INR 2,100 crore that have been diverted to non-tribal purposes and place them back into ring-fenced TSP accounts within 60 days.',
    department: 'Finance',
    deadline_raw: '60 days',
    deadline_iso: '2024-03-25',
    compliance_metric: 'Amount restored to TSP accounts + Compliance certificate from CAG',
    source_text: 'MoF shall restore diverted TSP health allocations of INR 2,100 crore to ring-fenced accounts within 60 days.',
    source_page: 8,
    source_bbox: { x1: 72, y1: 140, x2: 540, y2: 200, page: 8 },
    confidence: 0.82,
    priority: 'high',
    status: 'completed',
    assigned_to: 'Secretary, Tribal Affairs',
    verified_by: 'registrar@supremecourt.gov.in',
    created_at: '2024-01-26T09:00:00Z',
    judgment: { case_number: 'WP(C) 15632/2023', case_title: 'Tribal Welfare Society v. Union of India & Ministry of Health', court: 'Supreme Court of India' },
  },
  {
    id: 'a24',
    judgment_id: 'j7',
    directive_text: 'Ministry of Home Affairs shall deploy dedicated mobile medical vans with telemedicine connectivity to all 287 Forest Guard camps in Scheduled Areas within 8 months.',
    department: 'Home Affairs',
    deadline_raw: '8 months',
    deadline_iso: '2024-09-25',
    compliance_metric: 'Medical vans deployed / Forest Guard camps covered',
    source_text: 'MHA shall deploy mobile medical vans with telemedicine to all 287 Forest Guard camps within 8 months.',
    source_page: 10,
    source_bbox: { x1: 72, y1: 380, x2: 540, y2: 440, page: 10 },
    confidence: 0.71,
    priority: 'medium',
    status: 'overdue',
    assigned_to: 'Director, Forest Guard Services',
    created_at: '2024-01-26T09:00:00Z',
    judgment: { case_number: 'WP(C) 15632/2023', case_title: 'Tribal Welfare Society v. Union of India & Ministry of Health', court: 'Supreme Court of India' },
  },
  {
    id: 'a25',
    judgment_id: 'j7',
    directive_text: 'The Ministry of Social Justice and Empowerment shall launch a digital grievance portal for tribal healthcare complaints with 7-day resolution SLAs and monthly public dashboards within 3 months.',
    department: 'Social Justice',
    deadline_raw: '3 months',
    deadline_iso: '2024-04-25',
    compliance_metric: 'Portal launched + Complaints resolved within SLA / Total complaints',
    source_text: 'MoSJE shall launch tribal healthcare grievance portal with 7-day SLA and monthly dashboards within 3 months.',
    source_page: 12,
    source_bbox: { x1: 72, y1: 220, x2: 540, y2: 280, page: 12 },
    confidence: 0.78,
    priority: 'medium',
    status: 'completed',
    assigned_to: 'Secretary, Social Justice',
    verified_by: 'registrar@supremecourt.gov.in',
    created_at: '2024-01-26T09:00:00Z',
    judgment: { case_number: 'WP(C) 15632/2023', case_title: 'Tribal Welfare Society v. Union of India & Ministry of Health', court: 'Supreme Court of India' },
  },
  {
    id: 'a26',
    judgment_id: 'j4',
    directive_text: 'Ministry of Road Transport shall mandate fitment of advanced driver assistance systems (ADAS) including lane departure warning and automatic emergency braking in all new commercial vehicles above 3.5 tonnes from January 2026.',
    department: 'Infrastructure',
    deadline_raw: 'January 2026',
    deadline_iso: '2026-01-01',
    compliance_metric: 'Gazette notification issued + Vehicles compliant post-date',
    source_text: 'MoRTH shall mandate ADAS in all new commercial vehicles above 3.5 tonnes from January 2026.',
    source_page: 15,
    source_bbox: { x1: 72, y1: 300, x2: 540, y2: 360, page: 15 },
    confidence: 0.85,
    priority: 'medium',
    status: 'verified',
    assigned_to: 'Automotive Research Association of India',
    created_at: '2023-11-09T10:30:00Z',
    judgment: { case_number: 'WP(C) 8435/2022', case_title: 'National Road Safety Council v. Ministry of Road Transport', court: 'Supreme Court of India' },
  },
  {
    id: 'a27',
    judgment_id: 'j1',
    directive_text: 'The Ministry of Home Affairs shall direct all state governments to implement Graded Response Action Plan (GRAP) protocols automatically based on AQI thresholds without requiring separate executive orders.',
    department: 'Home Affairs',
    deadline_raw: '4 months',
    deadline_iso: '2024-07-15',
    compliance_metric: 'State notifications issued + GRAP auto-trigger mechanism operational',
    source_text: 'MHA shall direct all states to implement GRAP automatically based on AQI without separate executive orders.',
    source_page: 16,
    source_bbox: { x1: 72, y1: 440, x2: 540, y2: 500, page: 16 },
    confidence: 0.80,
    priority: 'high',
    status: 'completed',
    assigned_to: 'MHA Joint Secretary (States)',
    created_at: '2024-03-16T09:00:00Z',
    judgment: { case_number: 'WP(C) 1284/2023', case_title: 'Citizens for Clean Air v. Union of India', court: 'Supreme Court of India' },
  },
  {
    id: 'a28',
    judgment_id: 'j5',
    directive_text: 'The Social Justice Department of Uttar Pradesh shall identify and address last-mile water access for all Scheduled Caste and Scheduled Tribe hamlets that remain un-surveyed and ensure inclusion in JJM within 4 months.',
    department: 'Social Justice',
    deadline_raw: '4 months',
    deadline_iso: '2024-01-15',
    compliance_metric: 'SC/ST hamlets surveyed and covered / Total identified hamlets',
    source_text: 'UP Social Justice Dept shall address water access for all SC/ST hamlets and include in JJM within 4 months.',
    source_page: 11,
    source_bbox: { x1: 72, y1: 360, x2: 540, y2: 420, page: 11 },
    confidence: 0.73,
    priority: 'high',
    status: 'completed',
    assigned_to: 'UP SC/ST Welfare Officer',
    verified_by: 'registrar@allahabadhc.gov.in',
    created_at: '2023-09-15T08:00:00Z',
    judgment: { case_number: 'PIL No. 12/2023', case_title: 'Jan Swasthya Abhiyan v. State of Uttar Pradesh', court: 'High Court of Allahabad' },
  },
];

export const DEMO_DEPARTMENT_STATS: DepartmentStats[] = [
  {
    department: 'Environment',
    color_hex: '#2D6A4F',
    total: 9,
    completed: 4,
    in_progress: 3,
    overdue: 1,
    pending: 1,
    compliance_pct: 68,
    sparkline: [28, 34, 41, 47, 54, 61, 68],
  },
  {
    department: 'Finance',
    color_hex: '#D4831A',
    total: 8,
    completed: 3,
    in_progress: 2,
    overdue: 2,
    pending: 1,
    compliance_pct: 44,
    sparkline: [12, 18, 22, 28, 33, 40, 44],
  },
  {
    department: 'Health',
    color_hex: '#C1121F',
    total: 7,
    completed: 3,
    in_progress: 2,
    overdue: 1,
    pending: 1,
    compliance_pct: 57,
    sparkline: [30, 36, 41, 45, 50, 54, 57],
  },
  {
    department: 'Infrastructure',
    color_hex: '#5B8DB8',
    total: 7,
    completed: 4,
    in_progress: 2,
    overdue: 0,
    pending: 1,
    compliance_pct: 71,
    sparkline: [45, 52, 58, 62, 66, 69, 71],
  },
  {
    department: 'Education',
    color_hex: '#7F77DD',
    total: 3,
    completed: 2,
    in_progress: 1,
    overdue: 0,
    pending: 0,
    compliance_pct: 85,
    sparkline: [55, 62, 70, 76, 80, 83, 85],
  },
  {
    department: 'Home Affairs',
    color_hex: '#185FA5',
    total: 5,
    completed: 3,
    in_progress: 1,
    overdue: 1,
    pending: 0,
    compliance_pct: 60,
    sparkline: [20, 28, 35, 44, 51, 57, 60],
  },
  {
    department: 'Water Resources',
    color_hex: '#0891B2',
    total: 2,
    completed: 1,
    in_progress: 1,
    overdue: 0,
    pending: 0,
    compliance_pct: 55,
    sparkline: [10, 18, 26, 34, 42, 49, 55],
  },
  {
    department: 'Social Justice',
    color_hex: '#7C3AED',
    total: 3,
    completed: 2,
    in_progress: 0,
    overdue: 0,
    pending: 1,
    compliance_pct: 75,
    sparkline: [30, 40, 50, 58, 65, 71, 75],
  },
];
